const GET_VIDEOGAMES = "GET_VIDEOGAMES";
const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
const CLEAN_DETAIL = "CLEAN_DETAIL";
const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME";
const GET_GENRES = "GET_GENRES";
const CREATE_GAME = "CREATE_GAME";
const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";

export {
	GET_VIDEOGAMES,
	GET_VIDEOGAME_DETAIL,
	CLEAN_DETAIL,
	GET_VIDEOGAME_BY_NAME,
	GET_GENRES,
	CREATE_GAME,
	SET_SEARCH_QUERY,
};

//export const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";
//export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
//export const ORDER_BY_NAME = "ORDER_BY_NAME";
//export const ORDER_BY_RATING = "ORDER_BY_RATING";
